### ISSUE TITLE
remove requirement of non-destructive tag for tests to run by default

### ISSUE THREAD

**Issue by sshaar08** [mozilla/pytest-mozwebqa#147]
This makes it very hard to add to exiting testing frameworks without a lot of overhead. Can you pull it out the a config file if possible.

**Comment by rbillings** [comment]
This requirement was added because it's important to how these tests are run in our framework. It is very easy to change the default using commands [If you want to run destructive tests then you can specify the --destructive command line option.] If you have forked it into your local environment and want to use it for a separate framework you could remove all "destructive" references locally.

**Comment by davehunt** [comment]
I am considering if we could split this into a separate plugin. If we do that, you would be able to use pytest-mozwebqa without the destructive protection features. For now, @rbillings answered it best.

**Comment by sshaar08** [comment]
KK thanks guys i am making the changes locally now
